version: '3'

services:
   nginx:
      image: tienshawn/web:1.0
      ports:
         - "8080:8080"
      networks:
        - frontend

   backend:
      image: tienshawn/api:1.0
      expose:
         - "5000"
      ports:
         - "5000:5000"
      networks:
        - backend
        - frontend

   db:
      image: mongo:5.0.17
      restart: unless-stopped
      ports:
        - "27017:27017"
      networks:
        - backend

networks:
  backend:
    driver: bridge
  frontend:
    driver: bridge


